kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: {{ .Values.tiller_namespace_target }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.tiller_namespace_target }}-sa
  namespace:  {{ .Values.tiller_namespace_target }}
roleRef:
  kind: Role
  name: tiller-{{ .Values.tiller_namespace_target }}
  apiGroup: rbac.authorization.k8s.io
