kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-{{ .Values.tiller_namespace_target }}
  namespace:  {{ .Values.tiller_namespace_target }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tiller_namespace_target }}-sa
  namespace: {{ .Values.tiller_namespace_target }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-{{ .Values.tiller_namespace_target }}
  namespace:  {{ .Values.tiller_namespace_target }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: {{ .Values.tiller_namespace_target }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.tiller_namespace_target }}-sa
  namespace:  {{ .Values.tiller_namespace_target }}
roleRef:
  kind: Role
  name: tiller-{{ .Values.tiller_namespace_target }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: {{ .Values.tiller_namespace_target }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: {{ .Values.tiller_namespace_target }}
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: {{ .Values.tiller_image }}:{{ .Values.tiller_image_version }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      serviceAccountName: {{ .Values.tiller_namespace_target }}-sa2
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: {{ .Values.tiller_namespace_target }}
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}
